import { Mulish } from "@next/font/google";
import "./globals.css";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

import Navbar from "@/components/Navbar/Navbar";
import AuthProvider from "@/services/AuthProvider";
import StoreProvider from "@/allproviders/StoreProvider";
import SidebarProvider from "@/allproviders/sidebarProvider";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "HealCart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={mulish.className}>
        <AuthProvider>
          <StoreProvider>
            <Navbar />
            <SidebarProvider>{children}</SidebarProvider>
            <Toaster />
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
